### ISSUE TITLE
Add Search Card Component

### ISSUE THREAD

**Issue by simonjulianl** [simonjulianl/DeFentilz-Orbital#15]
Create the search component to search the facilities

**Comment by Amadeus-Winarto** [comment]
Basic layout done. Additional Functionalities to add: 
- Make card clickable. Add Event Listeners for clicks => open modal to expand and see description
- Lazy loading of cards in search page. Only load more cards when scrolled

**Comment by Amadeus-Winarto** [comment]
Clickable card done
