### ISSUE TITLE
Three-day view of Calendar doesn't show events for the same day

### ISSUE THREAD

**Issue by Amadeus-Winarto** [simonjulianl/DeFentilz-Orbital#42]
![image](https://user-images.githubusercontent.com/41280211/122792284-9b9ffb80-d2ec-11eb-8a1a-75ddf2fb9fec.png)
![image](https://user-images.githubusercontent.com/41280211/122792315-a35fa000-d2ec-11eb-8b86-c863b228d7c6.png)

**Comment by Amadeus-Winarto** [comment]
No idea why. Will look into it

**Comment by simonjulianl** [comment]
@Amadeus-Winarto is this fixed yet ?
