### ISSUE TITLE
Search Card too big for desktop

### ISSUE THREAD

**Issue by simonjulianl** [simonjulianl/DeFentilz-Orbital#61]
![Screenshot 2021-07-11 at 12 48 16 PM](https://user-images.githubusercontent.com/51783522/125183103-4483ab80-e246-11eb-8100-9c56383d14a5.png)

**Comment by Amadeus-Winarto** [comment]
See branch Profile for new update

**Comment by Amadeus-Winarto** [comment]
Addressed in Profile branch
